apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.username }}
  DB_PASSWORD: {{ .Values.secret.password }}
