apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}

